services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "9600:80/tcp"
    environment:
      TZ: '${TZ:-America/Chicago}'
      WEBPASSWORD: '${WEBPASSWORD:-admin}'
      FTLCONF_DNS_UPSTREAMS: '1.1.1.1;1.0.0.1'
      FTLCONF_dns_listeningMode: 'ALL'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
