services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "9600:80/tcp"
    environment:
      TZ: '${TZ:-America/Chicago}'
      WEBPASSWORD: '${WEBPASSWORD:-admin}'
      FTLCONF_dns_upstreams: 'gluetun#53'
      FTLCONF_dns_listeningMode: 'ALL'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    networks:
      - default
      - anime_torrent_streamer_default

networks:
  default:
  anime_torrent_streamer_default:
    external: true
